/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import qytetetjava.Sorpresa;

/**
 *
 * @author Angel
 */
public class VistaCartaSorpresa extends javax.swing.JPanel {

    /**
     * Creates new form VistaCartaSorpresa
     */
    public VistaCartaSorpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoSorpresa = new javax.swing.JTextArea();

        textoSorpresa.setEditable(false);
        textoSorpresa.setColumns(20);
        textoSorpresa.setRows(5);
        jScrollPane2.setViewportView(textoSorpresa);

        jTabbedPane1.addTab("Carta Sorpresa", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea textoSorpresa;
    // End of variables declaration//GEN-END:variables
    
    public void actualizar(Sorpresa sorpresa) {
        String xd;
        if (sorpresa == null)
            xd = "No hay carta sorpresa activa.";
        else
            xd = "Carta: " + sorpresa.getTexto() + "\nTipo: " + sorpresa.getTipoSorpresa() + "\nValor: " + sorpresa.getValor();
        
        textoSorpresa.setText(xd);
        
        this.repaint();
        this.revalidate();
    }
}
