/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import qytetetjava.Jugador;
import qytetetjava.TituloPropiedad;

/**
 *
 * @author Angel
 */
public class VistaJugador extends javax.swing.JPanel {

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jSaldo = new javax.swing.JLabel();
        jFactor = new javax.swing.JLabel();
        jEncarcelado = new javax.swing.JLabel();
        jProps = new javax.swing.JLabel();
        jCasilla = new javax.swing.JLabel();
        jCarta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        propiedades = new javax.swing.JTextArea();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Saldo:");

        jLabel3.setText("Factor especulador:");

        jLabel4.setText("Encarcelado:");

        jLabel5.setText("Casilla actual:");

        jLabel6.setText("Nº Propiedades:");

        jLabel7.setText("Carta cárcel:");

        jNombre.setText("-");

        jSaldo.setText("-");

        jFactor.setText("-");

        jEncarcelado.setText("-");

        jProps.setText("-");

        jCasilla.setText("-");

        jCarta.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNombre)
                    .addComponent(jSaldo)
                    .addComponent(jEncarcelado)
                    .addComponent(jFactor)
                    .addComponent(jCasilla)
                    .addComponent(jProps)
                    .addComponent(jCarta))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSaldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jEncarcelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFactor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCasilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProps)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jCarta))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugador", jPanel1);

        propiedades.setEditable(false);
        propiedades.setColumns(20);
        propiedades.setRows(5);
        jScrollPane2.setViewportView(propiedades);

        jTabbedPane1.addTab("Propiedades", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCarta;
    private javax.swing.JLabel jCasilla;
    private javax.swing.JLabel jEncarcelado;
    private javax.swing.JLabel jFactor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProps;
    private javax.swing.JLabel jSaldo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea propiedades;
    // End of variables declaration//GEN-END:variables

    public void actualizar(Jugador jugador) {
        this.jNombre.setText(jugador.getNombre());
        this.jSaldo.setText(jugador.getSaldoString());
        this.jEncarcelado.setText(jugador.getEncarceladoString());
        this.jFactor.setText(jugador.getFactorString());
        this.jCasilla.setText(jugador.getCasillaString());
        this.jProps.setText(jugador.getNumPropiedadesString());
        this.jCarta.setText(jugador.getCartaString());
        
        ArrayList<String> props = jugador.getPropiedades(3);
        String xd = "";
        
        if (props.isEmpty()) {
            xd = "Aún no tienes propiedades.";
        }
        
        for (String s : props) {
            xd += s + "\n";
        }
        
        propiedades.setText(xd);
        this.repaint();
        this.revalidate();
    }
}
